stages:
  - test
  - build
  - deploy

image: maven:3.6-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2/repository

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

test:
  stage: test
  script:
    - echo "Running tests"

build:
  stage: build
  script:
    - mvn package $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploy Started"
    - cd target/
    - ls -la *.jar
    - ssh -o StrictHostKeyChecking=no -tt root@$SERVER "systemctl stop gateway && sleep 10"
    - scp -o StrictHostKeyChecking=no app.jar root@$SERVER:/opt/spring-cloud-gateway
    - ssh -o StrictHostKeyChecking=no -tt root@$SERVER "systemctl start gateway && sleep 10"
    - ssh -o StrictHostKeyChecking=no -tt root@$SERVER "systemctl status gateway"
  only:
    - master
