server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: api-microservice
        uri: lb://api-microservice
        predicates:
        - Path=/microservice/**
        filters:
        - RewritePath=/bookstore/(?<segment>.*), /$\{segment}
      
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

