server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
      - id: api-bookstore
        uri: lb://api-bookstore
        predicates:
        - Path=/bookstore/**
        filters:
        - RewritePath=/bookstore/(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
        
    