server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: https://eureka.urbe.edu/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: spring-cloud-gateway  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: api-bookstore
        uri: lb://api-bookstore
        predicates:
        - Path=/bookstore/**
        filters:
        - RewritePath=/bookstore/(?<segment>.*), /$\{segment}
      - id: api-credential-validator
        uri: lb://api-credential-validator
        predicates:
        - Path=/credential/**
        filters:
        - RewritePath=/credential/(?<segment>.*), /$\{segment}
      - id: api-preinscription
        uri: lb://api-preinscription
        predicates:
        - Path=/preinscription/**
        filters:
        - RewritePath=/preinscription/(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG