server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: api-bookstore
        uri: lb://api-bookstore
        predicates:
        - Path=/bookstore/**
        filters:
        - RewritePath=/bookstore/(?<segment>.*), /$\{segment}
      - id: api-credential-validator
        uri: lb://api-credential-validator
        predicates:
        - Path=/credential/**
        filters:
        - RewritePath=/credential/(?<segment>.*), /$\{segment}
      - id: api-preinscription
        uri: lb://api-preinscription
        predicates:
        - Path=/preinscription/**
        filters:
        - RewritePath=/preinscription/(?<segment>.*), /$\{segment}
      - id: api-web-core
        uri: lb://api-web-core
        predicates:
        - Path=/web/**
        filters:
        - RewritePath=/web/(?<segment>.*), /$\{segment}
      - id: payment-notification
        uri: lb://payment-notification
        predicates:
        - Path=/wiretransfer/**
        filters:
        - RewritePath=/wiretransfer/(?<segment>.*), /$\{segment}  

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

